### ISSUE TITLE
Design and Debugen

### ISSUE THREAD

**Issue by Lizzyhara** [Kevkef/Brain-Racer#18]
1. Button Design
2. Skins of Coins are in the Back and not visible (Shop)
3. Layout Overhaul
4. Better Background
5. Add Sprites to Upgrade
6. Shop is not aktualisiert (no Problem since Add Coin is not a function in EndGame)

**Comment by Lizzyhara** [comment]
4, 2, 6 behebt

**Comment by Kevkef** [comment]
Wir sollten auch Color Schemes festlegen!

**Comment by Lizzyhara** [comment]
1, 3, 5 auch seit längerem
