### ISSUE TITLE
Issues mit Main Menu

### ISSUE THREAD

**Issue by Lizzyhara** [Kevkef/Brain-Racer#26]
Bitte alle Bugs die auftreten hier festhalten

**Comment by Kevkef** [comment]
Neustart des Spiels nach Kauf eines Items erforderlich

**Comment by Lizzyhara** [comment]
das ist leider nur bei dir der Fall müsste man zsm mal anschauen warum der bei dir auftritt

**Comment by Lizzyhara** [comment]
Behoben

**Comment by Kevkef** [comment]
Warum existiert ein Loading Screen, wenn man eine gespeicherte Map aufruft?

**Comment by Kevkef** [comment]
Der Loading Screen und das Main Menu überlagern sich kurz, wenn man auf new Game drückt (niegrige Prio)

**Comment by Lizzyhara** [comment]
behoben
